Feature/81 join scheme state icons
WorkerBeesTeam/DaiServerWebFront pull request #129
Opened 2021-07-19 07:32 UTC by ByMsx

2021-07-20 09:04 UTC, lirik90 requested changes
На самой странице схемы почему то остались обе иконки. Или это у меня с кэшем что то? (

2021-07-20 09:04 UTC, lirik90 commented on src/app/schemes/dashboard/dashboard.component.html
> +                <app-scheme-state-list [scheme]="scheme"></app-scheme-state-list>
Нужно чтобы подсказка при наведении была.

2021-07-20 09:04 UTC, lirik90 commented on src/app/schemes/list/list.component.html
> +    <app-scheme-state-list [scheme]="scheme"></app-scheme-state-list>
Подсказка нужна.

2021-07-20 09:04 UTC, lirik90 commented on src/app/schemes/scheme-state-list/scheme-state-list.component.html
> +      class="scheme-state-icon scheme-state-icon--{{status_class[most_bad_status]}}"
Чот тут кажется не работает. Иконка иногда просто серая. Видать баг какой то старый. Но не у всех конфигураций состояний 1 2 3 4, например у кондиционера нет.

2021-07-20 09:04 UTC, lirik90 commented on src/app/schemes/scheme-state-list/scheme-state-list.component.html
> +    </button>
Может подсказку куда то сюда влепить? А не в каждом месте как было раньше.

2021-07-20 09:04 UTC, lirik90 commented on src/app/schemes/scheme-state-list/scheme-state-list.component.ts
> +      }
Может лучше так?

```suggestion
  get isSchemeConnected(): boolean {
      switch (this.scheme.connect_state & 0b111) {
          case Connection_State.CS_CONNECTED:
          case Connection_State.CS_CONNECTED_JUST_NOW:
          case Connection_State.CS_CONNECTED_SYNC_TIMEOUT:
              return true;
      }
      return false;
```

2021-07-20 10:51 UTC, ByMsx commented on src/app/schemes/scheme-state-list/scheme-state-list.component.html
> +      class="scheme-state-icon scheme-state-icon--{{status_class[most_bad_status]}}"
@lirik90 
Серая, но пустая? Или есть какая-то надпись внутри? Я посмотрел на кондиционере иконку. Там сейчас 3 "серых" события и иконка серая, соответственно.

2021-07-20 11:23 UTC, lirik90 commented on src/app/schemes/scheme-state-list/scheme-state-list.component.html
> +      class="scheme-state-icon scheme-state-icon--{{status_class[most_bad_status]}}"
Что за серые события?

2021-07-21 03:12 UTC, lirik90 requested changes
Лампочка всё ещё серая.

2021-07-22 10:33 UTC, merged