Feature/17 scheme group editing
WorkerBeesTeam/DaiServerWebFront pull request #42
Opened 2021-01-20 13:05 UTC by ByMsx

2021-03-12 03:04 UTC, lirik90 requested changes

2021-03-12 03:04 UTC, lirik90 commented on src/app/app-routing.module.ts
> +  imports: [ RouterModule.forRoot(routes , { enableTracing: true } ) ],
Ты это для отладки раскоментировал или без этого не работает?

2021-03-12 03:04 UTC, lirik90 commented on src/app/app.component.html
> +        <li class="app-toolbar__menu-list-item">
Здесь нужно добавить *ngIf="isAdmin"

2021-03-12 03:04 UTC, lirik90 commented on src/app/scheme-groups/create-new-scheme-group/create-new-scheme-group.component.html
> +    <button mat-button i18n="@@SCHEME_GROUPS.CREATE" type="submit">Создать</button>
*ngIf="fg.value.id" then "Изменить" / "Удалить" else "Создать"

2021-03-12 03:04 UTC, lirik90 commented on src/app/scheme-groups/edit-scheme-group/edit-scheme-group.component.html
> +<app-users-and-devices *ngIf="group?.id" [id]="group.id"></app-users-and-devices>
app-users-and-devices -> app-users-and-schemes

2021-03-12 03:04 UTC, lirik90 commented on src/app/scheme-groups/scheme-groups.module.ts
> +import { UsersAndDevicesComponent } from './users-and-devices/users-and-devices.component';
UsersAndDevicesComponent -> UsersAndSchemesComponent

2021-03-12 03:04 UTC, lirik90 commented on src/app/scheme-groups/users-and-devices/users-and-devices.component.html
> +    <table mat-table [dataSource]="groupDevices">
Устройства -> Схемы, devices -> schemes

2021-03-12 03:04 UTC, lirik90 commented on src/app/scheme-groups/users-and-devices/users-and-devices.component.ts
> +export class UsersAndDevicesComponent implements OnInit, OnChanges {
Devices -> Schemes

2021-03-12 03:04 UTC, lirik90 commented on src/app/schemes/detail/detail.component.html
> +            [items]="deviceSchemeGroups"
deviceSchemeGroups -> schemeGroups

2021-03-12 03:04 UTC, lirik90 commented on src/app/schemes/detail/detail.component.ts
> +    deviceSchemeGroups: Scheme_Group[];
schemeGroups

2021-03-12 03:04 UTC, lirik90 commented on src/app/scheme-groups/item-scheme-groups-list/item-scheme-groups-list.component.ts
> +        this.schemesService.get_scheme_groups().subscribe(groups => this.schemeGroups = groups);
Только те которых нет в items

2021-03-12 03:04 UTC, lirik90 commented on src/app/scheme-groups/create-new-scheme-group/create-new-scheme-group.component.ts
> +    remove(group: Scheme_Group) {
Наверное так?
```ts
    remove() {
        let group: Scheme_Group = this.fg.value;
```

2021-03-12 03:04 UTC, lirik90 commented on src/app/scheme-groups/users-and-devices/users-and-devices.component.html
> +            <th mat-header-cell *matHeaderCellDef>Имя</th>
Пропущен i18n="@@SCHEME_GROUPS.NAME"

2021-03-12 03:04 UTC, lirik90 commented on src/app/user-settings/scheme-groups/scheme-groups.component.html
> +        (remove)="removeSchemeGroup($event)"
addToSchemeGroup или addUserToSchemeGroup
removeFromSchemeGroup или removeUserFromSchemeGroup

2021-03-12 09:49 UTC, ByMsx commented on src/app/app-routing.module.ts
> +  imports: [ RouterModule.forRoot(routes , { enableTracing: true } ) ],
Забыл.

2021-03-13 01:13 UTC, lirik90 requested changes

2021-03-13 01:13 UTC, lirik90 commented on src/app/schemes/schemes.service.ts
> +    }
```suggestion
    addUserToSchemeGroup(groupId: number, userId: number, role: any): Observable<{group_id: number, user_id: number, role: string}> {
        const url = this.v2_url + `scheme_group/${groupId}/user/${userId}/?role=${role}`;
        return this.http.post<{group_id: number, user_id: number, role: string}>(url, {});
    }
```

2021-03-13 01:13 UTC, lirik90 commented on src/app/schemes/schemes.service.ts
> +    }
```suggestion
    addSchemeToSchemeGroup(groupId: number, schemeId: number): Observable<{scheme_group_id: number, scheme_id: number}> {
        const url = this.v2_url + `scheme_group/${groupId}/scheme/${schemeId}/`;
        return this.http.post<{scheme_group_id: number, scheme_id: number}>(url, {});
    }
```

2021-03-13 01:13 UTC, lirik90 commented on src/app/schemes/schemes.service.ts
> +    }
```suggestion
    getSchemeGroupSchemes(id: number): Observable<Pick<Scheme, 'id' | 'name' | 'title'>[]> {
        const url = this.v2_url + `scheme_group/${id}/scheme/`;
        return this.http.get<Pick<Scheme, 'id' | 'name' | 'title'>[]>(url);
    }
```

2021-03-13 01:13 UTC, lirik90 commented on src/app/schemes/schemes.service.ts
> +    }
```suggestion
    getSchemeGroupUsers(id: number): Observable<UserHeaderWithRole[]> {
        const url = this.v2_url + `scheme_group/${id}/user/`;
        return this.http.get<UserHeaderWithRole[]>(url);
    }
```

2021-03-13 01:13 UTC, lirik90 commented on src/app/user.ts
> +export type UserHeaderWithRole = Pick<User, 'id' | 'first_name' | 'last_name' | 'username'> & { role: Group_User_Roles };
```suggestion

export type UserHeader = Pick<User, 'id' | 'first_name' | 'last_name' | 'username'>;
export type UserHeaderWithRole = UserHeader & { role: Group_User_Roles };
```

2021-03-13 01:13 UTC, lirik90 commented on src/app/schemes/schemes.service.ts
>      }
```suggestion
    getUsers(): Observable<UserHeader[]> {
        return this.http.get<UserHeader[]>(${this.v2_url} + `users/`);
    }
```

2021-03-13 01:13 UTC, lirik90 commented on src/app/schemes/schemes.service.ts
> +import {Auth_Group, Scheme, Scheme_Group, PaginatorApi, Group_User_Roles, User, UserHeaderWithRole} from '../user';
```suggestion
import {Auth_Group, Scheme, Scheme_Group, PaginatorApi, Group_User_Roles, User, UserHeader, UserHeaderWithRole} from '../user';
```

2021-03-13 01:13 UTC, lirik90 commented on src/app/schemes/detail/detail.component.ts
> +    addSchemeGroup($event: Scheme_Group) {
```suggestion
    addToSchemeGroup($event: Scheme_Group) {
```

2021-03-13 01:13 UTC, lirik90 commented on src/app/schemes/detail/detail.component.html
> +            (add)="addSchemeGroup($event)"
```suggestion
            (add)="addToSchemeGroup($event)"
```

2021-03-13 01:13 UTC, lirik90 commented on src/app/scheme-groups/item-scheme-groups-list/item-scheme-groups-list.component.ts
> +    schemeGroups: Scheme_Group[];
```suggestion
    schemeGroups: Scheme_Group[];
    private _schemeGroups: Scheme_Group[];
```

2021-03-13 01:13 UTC, lirik90 commented on src/app/scheme-groups/item-scheme-groups-list/item-scheme-groups-list.component.ts
> +            });
```suggestion
            .subscribe((groups) => this._schemeGroups = groups);
```

2021-03-13 01:13 UTC, lirik90 commented on src/app/scheme-groups/item-scheme-groups-list/item-scheme-groups-list.component.ts
> +        }
```suggestion
        }
        
        if (changes.items) {
            const items = changes.items.currentValue;
            this.schemeGroups = this._schemeGroups
                    .filter(group => !items.find(i => i.id === group.id));
        }
```

2021-03-13 05:30 UTC, merged