Feature/22 edit scheme from manage
WorkerBeesTeam/DaiServerWebFront pull request #43
Opened 2021-01-29 14:13 UTC by ByMsx

2021-03-12 10:33 UTC, lirik90 requested changes

2021-03-12 10:33 UTC, lirik90 commented on src/app/scheme/manage/device-item-detail-dialog/device-item-detail-dialog.component.html
> +    <a class="add-new_link" href="#" (click)="$event.preventDefault();newDevice()"><small i18n="@@SCHEME_DIALOGS.ADD_NEW">Добавить новый(ую)</small></a>
Эта строка должна быть выше

2021-03-12 10:33 UTC, lirik90 commented on src/app/scheme/scheme-routing.module.ts
> +                      path: 'by-section', component: ManageComponent,
```suggestion
                      path: 'sections', component: ManageComponent,
```

2021-03-12 10:33 UTC, lirik90 commented on src/app/schemes/dashboard/dashboard.component.html
> +             routerLink="/scheme/{{scheme?.name}}/elements/by-section">
```suggestion
             routerLink="/scheme/{{scheme?.name}}/elements/sections">
```

2021-03-12 10:33 UTC, lirik90 commented on src/app/scheme/elements/elements.component.html
> +    <a routerLink="by-section" routerLinkActive="active">Секции</a>
```suggestion
    <a routerLink="sections" routerLinkActive="active">Секции</a>
```

2021-03-12 10:33 UTC, lirik90 commented on src/app/scheme/scheme.service.ts
> +                        const key = SchemeService.getSchemeFieldKey(settingName);
Разве это не одно и тоже?
```suggestion
                        const key = settingName;
```

2021-03-12 10:33 UTC, lirik90 commented on src/app/scheme/scheme.service.ts
> +    }
Чот не могу понять, имена же одинаковые, зачем тут продублировано?
```suggestion
    private static getSchemeFieldKey(setting: Structure_Type): keyof Scheme_Detail {
        const keys: Structure_Type[] = [
            Structure_Type.ST_DEVICE, 
            Structure_Type.ST_SECTION,
            Structure_Type.ST_DEVICE_ITEM_TYPE,
            Structure_Type.ST_DIG_PARAM_TYPE,
            Structure_Type.ST_DIG_TYPE,
            Structure_Type.ST_DIG_STATUS_TYPE,
            Structure_Type.ST_DIG_STATUS_CATEGORY,
            Structure_Type.ST_DIG_MODE_TYPE,
            Structure_Type.ST_VALUE_VIEW,
        ];
        return keys.includes(setting) ? settings : undefined;
    }
```

2021-03-12 10:33 UTC, lirik90 commented on src/app/scheme/scheme.service.ts
> +                },
IDE конечно виднее. 🤦

2021-03-13 09:30 UTC, ByMsx commented on src/app/scheme/manage/device-item-detail-dialog/device-item-detail-dialog.component.html
> +    <a class="add-new_link" href="#" (click)="$event.preventDefault();newDevice()"><small i18n="@@SCHEME_DIALOGS.ADD_NEW">Добавить новый(ую)</small></a>
Нет, иначе mat-form-field уродски растянется и будет выглядеть так, будто ссылка вписана в выпадающем.

2021-03-13 10:09 UTC, ByMsx commented on src/app/scheme/scheme.service.ts
> +    }
Это имело смысл, т.к. запросы могли не совпадать с полями схемы.

2021-03-13 11:10 UTC, merged