Task 70: ability to set stepped manually for dataset
WorkerBeesTeam/DaiServerWebFront pull request #96
Opened 2021-06-24 07:25 UTC by ByMsx

2021-06-28 04:41 UTC, lirik90 requested changes

2021-06-28 04:41 UTC, lirik90 commented on src/app/scheme/reports/charts/charts.component.ts
> +        let dataset = this.genDataset('⚙️ ' + param.param.title, colorIndex, stepped, hsl, hidden);
Тут разве не так?
```suggestion
        if (stepped === null)
            stepped = param.param.value_type === DIG_Param_Value_Type.VT_BOOL;
        let dataset = this.genDataset('⚙️ ' + param.param.title, colorIndex, stepped, hsl, hidden);
```

2021-06-28 07:00 UTC, ByMsx commented on src/app/scheme/reports/charts/charts.component.ts
> +        let dataset = this.genDataset('⚙️ ' + param.param.title, colorIndex, stepped, hsl, hidden);
Запушил изменение.

2021-06-29 04:02 UTC, lirik90 commented
Пункт о том чтобы отображать скрытые шкалы в режиме редактирования не сделан.

2021-07-02 02:03 UTC, lirik90 approved these changes

2021-07-02 02:03 UTC, merged